DROP DATABASE IF EXISTS BANK;
CREATE DATABASE BANK;
USE BANK;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    ADDRES VARCHAR(50),
    EMAIL VARCHAR(50)
);

CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ACCOUNT_TYPE VARCHAR(20),
    BALANCE DECIMAL(10,2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TRANSACTION (
    TRANSACTION_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    TRANSACTION_TYPE VARCHAR(20),
    AMOUNT DECIMAL(10,2),
    TRANSACTION_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE WORKER (
    WORKER_ID INT PRIMARY KEY,
    TRANSACTION_ID INT,
    ACCOUNT_ID INT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE LOAN (
    LOAN_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    LOAN_DATE DATE,
    RETURN_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

