/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.bank.backoffice;

import org.apache.commons.text.WordUtils;

public class App {

    public static void main(String[] args) {
        var backOffice = new BackOffice(System.in, System.out);

        backOffice.start();
    }
}
