###
# Create New Account
POST http://localhost:8080/account
Content-Type: application/json

{
  "accountType": "Checking",
  "balance": 4500,
  "customer": {
    "id": 3,
    "firstName": null,
    "lastName": null,
    "address": null,
    "email": null,
    "loan": null,
    "account": null,
    "transaction": null
  },
  "worker": null
}

###
# Update Account
PUT http://localhost:8080/account/6
Content-Type: application/json

{
  "id": 6,
  "accountType": "Checking",
  "balance": 7000,
  "customer": {
    "id": 2,
    "firstName": null,
    "lastName": null,
    "address": null,
    "email": null,
    "loan": null,
    "account": null,
    "transaction": null
  },
  "worker": null
}

###
# Get Account
GET http://localhost:8080/account/4
Accept: application/json

###
# Get All Accounts
GET http://localhost:8080/account
Accept: application/json

###
# Delete Account
DELETE http://localhost:8080/account/6
