###
# Create New Customer
POST http://localhost:8080/customer
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "address": "123 Main St",
  "email": "john.doe@example.com"
}

###
# Update Customer
PUT http://localhost:8080/customer/5
Content-Type: application/json

{
  "id": 5,
  "firstName": "Jane",
  "lastName": "Doe",
  "address": "123 Elm St",
  "email": "jane.doe@example.com"
}

###
# Get Customer
GET http://localhost:8080/customer/1
Accept: application/json

###
# Get All Customers
GET http://localhost:8080/customer
Accept: application/json

###
# Delete Customer
DELETE http://localhost:8080/customer/5
