###
# Create New loan
POST http://localhost:3007/loan
Content-Type: application/json

{
  "loanDate": 1718402400000,
  "returnDate": 1723672800000,
  "customer": {
    "id": 3,
    "firstName": null,
    "lastName": null,
    "address": null,
    "email": null,
    "loan": null,
    "account": null,
    "transaction": null
  }
}

###
# Update Loan
PUT http://localhost:3007/loan/2
Content-Type: application/json

{
  "loanDate": 1718402400000,
  "returnDate": 1723672800000,
  "customer": {
    "id": 2,
    "firstName": null,
    "lastName": null,
    "address": null,
    "email": null,
    "loan": null,
    "account": null,
    "transaction": null
  }
}

###
# Get Loan
GET http://localhost:3007/loan/1
Accept: application/json

###
# Get All Loans
GET http://localhost:3007/loan
Accept: application/json

###
# Delete Loan
DELETE http://localhost:3007/loan/3
