###
# Create New loan
POST http://localhost:3009/customer
Content-Type: application/json

{
  "customerId": 1,
  "loan": {
    "loanDate": "2024-10-01",
    "returnDate": "2024-11-01"
  }
}

###
# Update Loan
PUT http://localhost:3009/customer/1
Content-Type: application/json

{
  "customerId": 1,
  "loan": {
    "loanDate": "2024-09-15",
    "returnDate": "2024-11-15"
  }
}

###
# Get Loan
GET http://localhost:3009/customer/1
Accept: application/json

###
# Get All Loans
GET http://localhost:3009/customer
Accept: application/json

###
# Delete Loan
DELETE http://localhost:3009/customer/2
