###
# Create New Worker
POST http://localhost:3007/worker
Content-Type: application/json

{
  "firstName": "Silviu",
  "lastName": "Balint",
  "transaction": null,
  "account": null
}


###
# Update Worker
PUT http://localhost:3007/worker/7
Content-Type: application/json

{
  "id": 7,
  "firstName": "Silviu",
  "lastName": "Sebastian",
  "transaction": null,
  "account": null
}

###
# Get Worker
GET http://localhost:3007/worker/5
Accept: application/json

###
# Get All Workers
GET http://localhost:3007/worker
Accept: application/json

###
## Delete Worker
DELETE http://localhost:3007/worker/7
